Thu, 18 Oct 2018 10:27:37 simplelogger.py[line:28] ERROR Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 50, in get_ci_tasks_recently_build
    result=CITaskService.get_product_ci_tasks(request, task_type, product_id).filter(LastHistory__exclude=(0,))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1252, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    split_subq=split_subq,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1214, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1078, in build_lookup
    lhs = self.try_transform(lhs, lookups[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1114, in try_transform
    (name, lhs.output_field.__class__.__name__))
django.core.exceptions.FieldError: Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Thu, 18 Oct 2018 10:27:37 simplelogger.py[line:28] ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/views/ci_task_view.py", line 165, in more_dashboard_task_list
    result=page_worker.dashboard_more_task_list(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/pagefactory/ci_task_pageworker.py", line 103, in dashboard_more_task_list
    dm_ci_tasks = CITaskService.filter_tasks(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in filter_tasks
    result=[task for task in result if task.Project in eval(project_ids)]
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in <listcomp>
    result=[task for task in result if task.Project in eval(project_ids)]
TypeError: eval() arg 1 must be a string, bytes or code object
Thu, 18 Oct 2018 10:29:21 simplelogger.py[line:28] ERROR Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 50, in get_ci_tasks_recently_build
    result=CITaskService.get_product_ci_tasks(request, task_type, product_id).filter(LastHistory__exclude=(0,))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1252, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    split_subq=split_subq,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1214, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1078, in build_lookup
    lhs = self.try_transform(lhs, lookups[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1114, in try_transform
    (name, lhs.output_field.__class__.__name__))
django.core.exceptions.FieldError: Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Thu, 18 Oct 2018 10:29:21 simplelogger.py[line:28] ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/views/ci_task_view.py", line 165, in more_dashboard_task_list
    result=page_worker.dashboard_more_task_list(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/pagefactory/ci_task_pageworker.py", line 103, in dashboard_more_task_list
    dm_ci_tasks = CITaskService.filter_tasks(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in filter_tasks
    result=[task for task in result if task.Project in eval(project_ids)]
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in <listcomp>
    result=[task for task in result if task.Project in eval(project_ids)]
TypeError: eval() arg 1 must be a string, bytes or code object
Thu, 18 Oct 2018 10:29:58 simplelogger.py[line:28] ERROR Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 50, in get_ci_tasks_recently_build
    result=CITaskService.get_product_ci_tasks(request, task_type, product_id).filter(LastHistory__exclude=(0,))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1252, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    split_subq=split_subq,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1214, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1078, in build_lookup
    lhs = self.try_transform(lhs, lookups[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1114, in try_transform
    (name, lhs.output_field.__class__.__name__))
django.core.exceptions.FieldError: Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Thu, 18 Oct 2018 10:29:58 simplelogger.py[line:28] ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/views/ci_task_view.py", line 165, in more_dashboard_task_list
    result=page_worker.dashboard_more_task_list(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/pagefactory/ci_task_pageworker.py", line 103, in dashboard_more_task_list
    dm_ci_tasks = CITaskService.filter_tasks(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in filter_tasks
    result=[task for task in result if task.Project in eval(project_ids)]
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in <listcomp>
    result=[task for task in result if task.Project in eval(project_ids)]
TypeError: eval() arg 1 must be a string, bytes or code object
Thu, 18 Oct 2018 10:31:15 simplelogger.py[line:28] ERROR Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 50, in get_ci_tasks_recently_build
    result=CITaskService.get_product_ci_tasks(request, task_type, product_id).filter(LastHistory__exclude=(0,))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1252, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    split_subq=split_subq,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1214, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1078, in build_lookup
    lhs = self.try_transform(lhs, lookups[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1114, in try_transform
    (name, lhs.output_field.__class__.__name__))
django.core.exceptions.FieldError: Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Thu, 18 Oct 2018 10:31:15 simplelogger.py[line:28] ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/views/ci_task_view.py", line 165, in more_dashboard_task_list
    result=page_worker.dashboard_more_task_list(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/pagefactory/ci_task_pageworker.py", line 103, in dashboard_more_task_list
    dm_ci_tasks = CITaskService.filter_tasks(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in filter_tasks
    result=[task for task in result if task.Project in eval(project_ids)]
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in <listcomp>
    result=[task for task in result if task.Project in eval(project_ids)]
TypeError: eval() arg 1 must be a string, bytes or code object
Thu, 18 Oct 2018 10:32:07 simplelogger.py[line:28] ERROR Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 50, in get_ci_tasks_recently_build
    result=CITaskService.get_product_ci_tasks(request, task_type, product_id).filter(LastHistory__exclude=(0,))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1252, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    split_subq=split_subq,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1214, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1078, in build_lookup
    lhs = self.try_transform(lhs, lookups[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1114, in try_transform
    (name, lhs.output_field.__class__.__name__))
django.core.exceptions.FieldError: Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Thu, 18 Oct 2018 10:32:07 simplelogger.py[line:28] ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/views/ci_task_view.py", line 165, in more_dashboard_task_list
    result=page_worker.dashboard_more_task_list(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/pagefactory/ci_task_pageworker.py", line 103, in dashboard_more_task_list
    dm_ci_tasks = CITaskService.filter_tasks(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in filter_tasks
    result=[task for task in result if task.Project in eval(project_ids)]
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in <listcomp>
    result=[task for task in result if task.Project in eval(project_ids)]
TypeError: eval() arg 1 must be a string, bytes or code object
Thu, 18 Oct 2018 10:32:48 simplelogger.py[line:28] ERROR Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 50, in get_ci_tasks_recently_build
    result=CITaskService.get_product_ci_tasks(request, task_type, product_id).filter(LastHistory__exclude=(0,))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1252, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    split_subq=split_subq,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1214, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1078, in build_lookup
    lhs = self.try_transform(lhs, lookups[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1114, in try_transform
    (name, lhs.output_field.__class__.__name__))
django.core.exceptions.FieldError: Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Thu, 18 Oct 2018 10:32:48 simplelogger.py[line:28] ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/views/ci_task_view.py", line 165, in more_dashboard_task_list
    result=page_worker.dashboard_more_task_list(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/pagefactory/ci_task_pageworker.py", line 103, in dashboard_more_task_list
    dm_ci_tasks = CITaskService.filter_tasks(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in filter_tasks
    result=[task for task in result if task.Project in eval(project_ids)]
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in <listcomp>
    result=[task for task in result if task.Project in eval(project_ids)]
TypeError: eval() arg 1 must be a string, bytes or code object
Thu, 18 Oct 2018 10:35:32 simplelogger.py[line:28] ERROR Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 50, in get_ci_tasks_recently_build
    result=CITaskService.get_product_ci_tasks(request, task_type, product_id).filter(LastHistory__exclude=(0,))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1252, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    split_subq=split_subq,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1214, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1078, in build_lookup
    lhs = self.try_transform(lhs, lookups[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1114, in try_transform
    (name, lhs.output_field.__class__.__name__))
django.core.exceptions.FieldError: Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Thu, 18 Oct 2018 10:35:32 simplelogger.py[line:28] ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/views/ci_task_view.py", line 165, in more_dashboard_task_list
    result=page_worker.dashboard_more_task_list(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/doraemon/ci/pagefactory/ci_task_pageworker.py", line 103, in dashboard_more_task_list
    dm_ci_tasks = CITaskService.filter_tasks(request)
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in filter_tasks
    result=[task for task in result if task.Project in eval(project_ids)]
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_service.py", line 118, in <listcomp>
    result=[task for task in result if task.Project in eval(project_ids)]
TypeError: eval() arg 1 must be a string, bytes or code object
Thu, 18 Oct 2018 10:40:12 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:12 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:12 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:13 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:13 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:13 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:13 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:13 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:13 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:13 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 10:40:13 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 18 Oct 2018 11:07:32 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 18 Oct 2018 11:07:40 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
