Tue, 16 Oct 2018 14:44:21 simplelogger.py[line:28] ERROR list index out of range
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 408, in get_byvalue
    result=super(IssueConfigFieldManager,self).get_queryset().filter(Value=config_value)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 307, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
Tue, 16 Oct 2018 15:16:57 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:16:59 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:00 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:00 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:01 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:01 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:02 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:03 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:03 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:04 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:04 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:04 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:05 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:05 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:06 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
Tue, 16 Oct 2018 15:17:06 simplelogger.py[line:28] ERROR 'AnonymousUser' object has no attribute 'extend_info'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/Teamcat/teamcat_web/doraemon/business/ucenter/account_service.py", line 35, in get_avatar_url
    if user.extend_info:
AttributeError: 'AnonymousUser' object has no attribute 'extend_info'
